"""
AI RAG (Retrieval-Augmented Generation) chat service.
Uses LangChain + FAISS + OpenAI for context-aware streaming Q&A.
"""
import os
import logging
from typing import AsyncIterator, List, Dict, Any, Optional
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_community.vectorstores import FAISS
from langchain.chains import ConversationalRetrievalChain
from langchain.prompts import PromptTemplate
from langchain.schema import HumanMessage, AIMessage
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, and_

from app.core.config import settings
from app.models.models import File, DocumentChunk

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = """You are DocuMind AI, an expert assistant that answers questions based on uploaded documents, audio, and video content.

Use the following retrieved context to answer the user's question accurately and concisely.
If the context doesn't contain enough information, say so honestly — do not hallucinate.
Always cite the source material when possible.

Context:
{context}

Chat History:
{chat_history}

Question: {question}

Answer:"""


def load_faiss_index(index_path: str) -> Optional[FAISS]:
    """Load a FAISS index from disk. Returns None if not found."""
    if not os.path.exists(index_path):
        return None
    embeddings = OpenAIEmbeddings(
        model=settings.OPENAI_EMBEDDING_MODEL,
        openai_api_key=settings.OPENAI_API_KEY,
    )
    return FAISS.load_local(index_path, embeddings, allow_dangerous_deserialization=True)


def merge_faiss_indexes(index_paths: List[str]) -> Optional[FAISS]:
    """Merge multiple FAISS indexes for multi-file querying."""
    merged = None
    for path in index_paths:
        index = load_faiss_index(path)
        if index is None:
            continue
        if merged is None:
            merged = index
        else:
            merged.merge_from(index)
    return merged


def format_chat_history(messages: List[Dict]) -> List:
    """Convert DB chat messages to LangChain message objects."""
    history = []
    for msg in messages:
        if msg["role"] == "user":
            history.append(HumanMessage(content=msg["content"]))
        else:
            history.append(AIMessage(content=msg["content"]))
    return history


async def stream_rag_response(
    question: str,
    file_ids: List[int],
    chat_history: List[Dict],
    db: AsyncSession,
) -> AsyncIterator[str]:
    """
    Stream a RAG response for a given question.
    Yields tokens as they are generated by the LLM.
    """
    # Load relevant FAISS indexes
    index_paths = []
    if file_ids:
        result = await db.execute(
            select(File.faiss_index_path).where(
                and_(File.id.in_(file_ids), File.faiss_index_path.isnot(None))
            )
        )
        index_paths = [row[0] for row in result.fetchall() if row[0]]
    else:
        result = await db.execute(
            select(File.faiss_index_path).where(File.faiss_index_path.isnot(None))
        )
        index_paths = [row[0] for row in result.fetchall() if row[0]]

    if not index_paths:
        yield "I don't have any processed documents to search through. Please upload and process a file first."
        return

    vector_store = merge_faiss_indexes(index_paths)
    if vector_store is None:
        yield "Could not load document indexes. Please re-process your files."
        return

    # Retrieve relevant chunks
    retriever = vector_store.as_retriever(
        search_type="similarity",
        search_kwargs={"k": settings.TOP_K_RESULTS},
    )
    relevant_docs = await retriever.ainvoke(question)

    # Build context string with source metadata
    context_parts = []
    sources = []
    for doc in relevant_docs:
        context_parts.append(doc.page_content)
        meta = doc.metadata
        sources.append({
            "file_id": meta.get("file_id"),
            "chunk_index": meta.get("chunk_index"),
            "start_time": meta.get("start_time"),
            "end_time": meta.get("end_time"),
            "snippet": doc.page_content[:200],
            "score": meta.get("score", 0.0),
        })

    context = "\n\n---\n\n".join(context_parts)
    history_text = "\n".join(
        [f"{m['role'].capitalize()}: {m['content']}" for m in chat_history[-6:]]
    )

    # Build prompt
    prompt = SYSTEM_PROMPT.format(
        context=context,
        chat_history=history_text,
        question=question,
    )

    # Stream from OpenAI
    llm = ChatOpenAI(
        model=settings.OPENAI_MODEL,
        openai_api_key=settings.OPENAI_API_KEY,
        streaming=True,
        temperature=0.3,
    )

    full_response = ""
    async for chunk in llm.astream(prompt):
        token = chunk.content
        if token:
            full_response += token
            yield token

    # Yield sources as final JSON marker for frontend parsing
    import json
    yield f"\n\n__SOURCES__{json.dumps(sources)}__END_SOURCES__"


async def get_relevant_chunks(
    query: str,
    file_ids: List[int],
    top_k: int = 5,
    db: AsyncSession = None,
) -> List[Dict[str, Any]]:
    """
    Perform semantic search and return top-k chunks with metadata.
    Used by timestamp search and citation endpoints.
    """
    result = await db.execute(
        select(File.faiss_index_path, File.id).where(
            and_(File.id.in_(file_ids), File.faiss_index_path.isnot(None))
        )
    )
    rows = result.fetchall()
    if not rows:
        return []

    index_paths = [r[0] for r in rows if r[0]]
    vector_store = merge_faiss_indexes(index_paths)
    if not vector_store:
        return []

    docs_scores = await vector_store.asimilarity_search_with_score(query, k=top_k)
    chunks = []
    for doc, score in docs_scores:
        meta = doc.metadata
        chunks.append({
            "file_id": meta.get("file_id"),
            "chunk_index": meta.get("chunk_index"),
            "content": doc.page_content,
            "start_time": meta.get("start_time"),
            "end_time": meta.get("end_time"),
            "score": float(1 - score),  # Convert L2 distance to similarity
        })
    return chunks
